language: c

sudo: false

before_install:
    - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

install:
    - arduino --install-library "USB Host Shield Library 2.0,Kalman Filter Library"
    - arduino --pref "boardsmanager.additional.urls=https://raw.githubusercontent.com/TKJElectronics/Balanduino/master/package_tkj_balanduino_index.json" --save-prefs
    - arduino --install-boards Balanduino:avr

script:
    - arduino --verify --board Balanduino:avr:balanduino:rev=rev12 $PWD/Firmware/Balanduino/Balanduino.ino
    - arduino --verify --board Balanduino:avr:balanduino:rev=rev13 $PWD/Firmware/Balanduino/Balanduino.ino
